[book]
authors = ["Tab Liu"]
language = "zh-CN"
multilingual = false

title = "RVOS学习笔记"
description = "tab liu"

[rust]
edition = "2021"

# 右上角的github图标链接
[output.html]
no-section-label = true                                     # 左边不显示序号,如"1.1", "1.2.1"
git-repository-url = "https://github.com/tab-liu/book_rvos"

additional-css = ["theme/style.css"]
additional-js = ["theme/sidebar.js"]
